INSERT INTO RESTAURANT (NAME) VALUES  ('Рыбный ресторан');
INSERT INTO RESTAURANT (NAME) VALUES  ('Кофейня');
INSERT INTO RESTAURANT (NAME) VALUES  ('Столовая');
INSERT INTO RESTAURANT (NAME) VALUES  ('Шашлычная');


INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Рыба',100, 100000);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Устрицы',200, 100000);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Мидии',300, 100000);

INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Булочка',150, 100001);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Кофе',50, 100001);

INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Щи',150, 100002);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Хлеб',20, 100002);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Компот',70, 100002);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Пюре',120, 100002);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Мясо',220, 100002);

INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Шашлык',350, 100003);
INSERT INTO MENU (NAME, PRICE, RESTAURANT_ID ) VALUES  ('Пиво',150, 100003);

INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES  ('Admin','admin@ya.ru','admin');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES  ('User','user@ya.ru','user');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES  ('User1','user1@ya.ru','user');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES  ('User2','user2@ya.ru','user');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES  ('User3','user3@ya.ru','user');
INSERT INTO USERS (NAME, EMAIL, PASSWORD) VALUES  ('User4','user4@ya.ru','user');

INSERT INTO user_role (role, user_id) VALUES ('ADMIN', 100016);
INSERT INTO user_role (role, user_id) VALUES ('USER', 100017);
INSERT INTO user_role (role, user_id) VALUES ('USER', 100018);
INSERT INTO user_role (role, user_id) VALUES ('USER', 100019);
INSERT INTO user_role (role, user_id) VALUES ('USER', 100020);
INSERT INTO user_role (role, user_id) VALUES ('USER', 100021);

INSERT INTO votes (restaurant_id, user_id) VALUES (100000, 100017);
INSERT INTO votes (restaurant_id, user_id) VALUES (100000, 100018);