

INSERT INTO RESTAURANT (NAME) VALUES  ('Рыбный ресторан');
INSERT INTO RESTAURANT (NAME) VALUES  ('Кофейня');
INSERT INTO RESTAURANT (NAME) VALUES  ('Столовая');
INSERT INTO RESTAURANT (NAME) VALUES  ('Шашлычная');

